- package.json
- pnpm-lock.yaml
- vite.config.ts
> chore: upgrade to pnpm 8

- .github/workflows/ci.yml
- .husky/commit-msg
- .husky/pre-commit
- .prettierrc.json
- commitlint.config.js
- package.json
- pnpm-lock.yaml
- postcss.config.js
- scripts/dist-build.js
- scripts/postinstall.js
- scripts/utils.js
- src/components/buttons/Button.stories.ts
- src/components/buttons/Button.vue
- src/composables/theme.ts
- src/consts/colors.ts
- src/index.ts
- src/stories/themes/typography-classes-list.ts
- src/types/theme.ts
- tailwind.config.js
- vite.config.ts
> chore: introduce lint-staged and husky

- .codecov.yml
- .eslintignore
- .github/workflows/ci.yml
> ci: enables tests and coverage on ci

- .github/workflows/ci.yml
> ci: add storybook build step on ci

- example/cypress/e2e/forms/checkbox.cy.ts
- example/src/views/HomeView.vue
- package.json
- pnpm-lock.yaml
- src/components/buttons/Button.spec.ts
- src/components/buttons/Button.vue
- src/components/forms/checkbox/Checkbox.spec.ts
- src/components/forms/checkbox/Checkbox.stories.ts
- src/components/forms/checkbox/Checkbox.vue
- src/composables/icons.ts
- src/index.ts
- src/vue-shim.d.ts
- tests/setup-files/setup.ts
- tsconfig.build.json
- vite.config.ts
> feat: checkbox component

- example/src/main.ts
- example/src/views/HomeView.vue
- src/components/buttons/Button.spec.ts
- src/components/buttons/Button.stories.ts
- src/components/buttons/Button.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/icons/Icon.spec.ts
- tailwind.config.cjs
> feat: update button component

- example/src/views/HomeView.vue
- src/components/forms/revealable-text-field/RevealableTextField.spec.ts
- src/components/forms/revealable-text-field/RevealableTextField.stories.ts
- src/components/forms/revealable-text-field/RevealableTextField.vue
- src/components/icons/Icon.vue
- src/composables/icons.ts
- src/index.ts
> feat: revealable-input

- src/components/forms/text-field/TextField.vue
> fix: remove input outline

- example/cypress/e2e/alert.cy.ts
- example/src/views/HomeView.vue
- src/components/alerts/Alert.spec.ts
- src/components/alerts/Alert.stories.ts
- src/components/alerts/Alert.vue
- src/index.ts
- src/styles/colors.scss
- tailwind.config.cjs
> feat: create alert component

- example/src/views/ButtonView.vue
- src/components/buttons/button/Button.spec.ts
- src/components/buttons/button/Button.stories.ts
- src/components/buttons/button/Button.vue
- src/components/progress/Progress.spec.ts
- src/components/progress/Progress.stories.ts
- src/components/progress/Progress.vue
- src/composables/icons.ts
- src/styles/colors.scss
> feat: add loading spinner to button

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
- README.md
- example/README.md
- package.json
> Adds publish config for npm

- package.json
> chore: add cjs extension to lint-staged

- .storybook/preview.scss
- .storybook/preview.ts
- src/components/buttons/button/Button.vue
- src/components/forms/checkbox/Checkbox.spec.ts
- src/components/forms/checkbox/Checkbox.vue
- src/components/forms/radio-button/radio-group/RadioGroup.spec.ts
- src/components/forms/radio-button/radio-group/RadioGroup.vue
- src/components/forms/radio-button/radio/Radio.spec.ts
- src/components/forms/radio-button/radio/Radio.vue
- src/components/forms/text-field/TextField.spec.ts
- src/components/forms/text-field/TextField.vue
- src/components/steppers/FooterStepper.vue
- src/components/steppers/Stepper.vue
- src/components/steppers/StepperCustomIcon.vue
- src/components/steppers/StepperIcon.vue
- src/composables/theme.ts
- src/style.scss
- src/styles/colors.scss
- tailwind.config.cjs
> feat: define text color

- vite.config.ts
> fix: font face not externalized

- src/components/alerts/Alert.vue
> fix: alert title optional

- package.json
- pnpm-lock.yaml
> chore: adds bumpp and release script

- package.json
- scripts/prepare.cjs
- src/components/alerts/Alert.vue
- src/components/buttons/button-group/ButtonGroup.vue
- src/components/buttons/button/Button.vue
- src/components/chips/Chip.vue
- src/components/forms/auto-complete/AutoComplete.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/forms/radio-button/radio-group/RadioGroup.vue
- src/components/forms/radio-button/radio/Radio.vue
- src/components/forms/revealable-text-field/RevealableTextField.vue
- src/components/forms/text-field/TextField.vue
- src/components/icons/Icon.vue
- src/components/logos/Logo.vue
- src/components/progress/Progress.vue
- src/components/steppers/FooterStepper.vue
- src/components/steppers/Stepper.vue
- tailwind.config.ts
> feat: add define options name to components

- src/components/forms/text-field/TextField.vue
> fix: remove tab index from textfield div

- example/src/main.ts
- package.json
Fixes https://nodejs.org/api/deprecations.html#DEP0166
Closes #(issue_number)
> fix!: updates default exports path to /dist

- src/components/forms/auto-complete/AutoComplete.stories.ts
- src/components/forms/auto-complete/AutoComplete.vue
Add virtual scroller to the autocomplete component, so it can handle large amount of the data.
> feat: add virtual scroller to autocomplete

- src/components/forms/revealable-text-field/RevealableTextField.vue
- src/components/forms/text-field/TextField.vue
Add a little adjustment for text field, when the field is autofilled.
> style: autofill on text field

- .storybook/preview.ts
- package.json
- pnpm-lock.yaml
- src/components/buttons/button-group/ButtonGroup.stories.ts
- src/components/buttons/button/Button.stories.ts
- src/composables/theme.ts
- src/index.ts
- vite.config.ts
> fix: adaptive theme and remove unhead

- src/components/steppers/Stepper.stories.ts
- src/components/steppers/Stepper.vue
- src/components/steppers/StepperCustomIcon.vue
- src/components/steppers/StepperIcon.vue
- src/types/stepper.ts
Add min width to the stepper circle. and also for the custom one, automatically set the state by passed step.
> fix: stepper style and simplify custom steps

- package.json
- src/components/index.ts
- src/composables/index.ts
- src/index.ts
- vite.config.ts
> fix: allows import from /components and /composables

- package.json
- pnpm-lock.yaml
- vite.config.ts
> fix: adds typeVersions to fix subpath import errors

- package.json
> fix: adds type module to package.json

- src/components/steppers/Stepper.vue
- src/style.scss
> feat(stepper): keep active step visible on screen

- src/components/alerts/Alert.vue
- src/theme/index.ts
> feat: improvement for alert

- src/components/logos/Logo.vue
- src/components/steppers/StepperCustomIcon.vue
- src/composables/theme.ts
> fix: adjust color to support custom theme

- scripts/generate-icons.cjs
- src/components/alerts/Alert.vue
- src/components/forms/text-field/TextField.vue
- src/components/icons/Icon.vue
> refactor: adds icon type for autocompletion

- example/cypress/e2e/overlays/tooltip.cy.ts
- example/src/views/TooltipView.vue
- src/components/overlays/tooltip/Tooltip.spec.ts
- src/components/overlays/tooltip/Tooltip.stories.ts
- src/components/overlays/tooltip/Tooltip.vue
> fix: update tooltip component to easier migration from vuetify

- src/components/alerts/Alert.vue
- src/components/chips/Chip.vue
- src/components/overlays/dialog/Dialog.vue
> fix: update chip and dialog component

- src/components/forms/auto-complete/AutoComplete.vue
- src/components/forms/text-field/TextField.spec.ts
- src/components/forms/text-field/TextField.stories.ts
- src/components/forms/text-field/TextField.vue
> feat: add listener to autocomplete component

- example/cypress/e2e/tabs.cy.ts
- example/src/App.vue
- example/src/main.ts
- example/src/router/index.ts
- example/src/views/TabView.vue
- package.json
- pnpm-lock.yaml
- src/components/buttons/button/Button.vue
- src/components/index.ts
- src/components/steppers/StepperCustomIcon.vue
- src/components/tabs/tab-item/TabItem.spec.ts
- src/components/tabs/tab-item/TabItem.vue
- src/components/tabs/tab-items/TabItems.spec.ts
- src/components/tabs/tab-items/TabItems.vue
- src/components/tabs/tab/Tab.spec.ts
- src/components/tabs/tab/Tab.vue
- src/components/tabs/tabs/Tabs.spec.ts
- src/components/tabs/tabs/Tabs.stories.ts
- src/components/tabs/tabs/Tabs.vue
- vite.config.ts
> feat: tabs component

- .github/workflows/ci.yml
- example/src/views/DataTableView.vue
- example/src/views/TabView.vue
- src/components/overlays/badge/Badge.vue
- src/components/tables/DataTable.vue
- src/components/tabs/tab-item/TabItem.vue
> fix(DataTable): improve type inference by introducing generics

- src/components/cards/Card.vue
> fix: update card bg color

- src/components/buttons/button/Button.vue
> fix: update loading state in button

- src/components/overlays/tooltip/Tooltip.spec.ts
- src/composables/popper.ts
> fix: tooltip timeout bug

- package.json
> chore: release v0.5.1

- src/components/tables/DataTable.vue
> feat(DataTable): add body append slot

- src/components/tables/DataTable.stories.ts
- src/components/tables/DataTable.vue
> feat: add striped props to table

- example/cypress/e2e/card.cy.ts
- src/components/cards/Card.spec.ts
- src/components/cards/CardHeader.vue
> fix(Card): change header to h6

- example/cypress/e2e/overlays/tooltip.cy.ts
- example/src/views/TooltipView.vue
- src/components/overlays/tooltip/Tooltip.spec.ts
- src/components/overlays/tooltip/Tooltip.vue
> fix: remove activator div from tooltip

- example/src/assets/main.css
- example/src/components/AppNav.vue
- example/src/views/ButtonView.vue
- example/src/views/CheckboxView.vue
- src/components/buttons/button-group/ButtonGroup.stories.ts
- src/components/buttons/button-group/ButtonGroup.vue
- src/components/buttons/button/Button.vue
- src/components/chips/Chip.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/forms/radio-button/radio/Radio.vue
- src/components/overlays/badge/Badge.vue
- src/components/steppers/FooterStepper.vue
> Pulling changes from compat

- src/components/cards/Card.vue
> style(Card): adjust Card footer padding

- package.json
- src/index.ts
> Expose contextColors 

- src/components/buttons/button/Button.stories.ts
- src/components/buttons/button/Button.vue
> feat(Button): add variant list to button

- example/cypress/e2e/data-table.cy.ts
- example/src/assets/main.css
- example/src/main.ts
- example/src/stores/counter.ts
> fix(DataTable): external pagination, and sticky table header

- package.json
> chore: release v0.9.0

- .github/renovate.json5
> chore: introduce renovate config

- package.json
- pnpm-lock.yaml
- scripts/new-story.ts
- tsconfig.eslint.json
> chore: add script to create new components

- src/components/forms/text-field/TextField.vue
> fix(TextField): styling bug for text-field label

- example/cypress/e2e/forms/switch.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/SwitchView.vue
- src/components/forms/switch/Switch.spec.ts
- src/components/forms/switch/Switch.stories.ts
- src/components/forms/switch/Switch.vue
- src/components/index.ts
> feat(Switch): introduce switch component

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
- src/index.ts
> CI and defaults changes

- example/src/views/AutoCompleteView.vue
- src/components/forms/auto-complete/AutoComplete.stories.ts
- src/components/forms/auto-complete/AutoComplete.vue
- src/components/forms/auto-complete/AutoCompleteSelection.vue
- src/composables/forms/auto-complete/index.ts
- src/consts/forms/auto-complete/index.ts
- src/utils/forms/auto-complete/index.ts
> feat(AutoComplete): introduce generics in auto-complete

- src/components/forms/text-field/TextField.stories.ts
- src/components/forms/text-field/TextField.vue
> fix(TextField): truncate label overflow if it's too long

- src/components/forms/switch/Switch.vue
> style: improve styling for Switch

- src/components/forms/switch/Switch.vue
> style(Switch): update style for the highlight

- example/cypress/e2e/overlays/menu.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/MenuView.vue
- src/components/index.ts
- src/components/overlays/menu/Menu.spec.ts
- src/components/overlays/menu/Menu.stories.ts
- src/components/overlays/menu/Menu.vue
- src/components/overlays/tooltip/Tooltip.spec.ts
- src/components/overlays/tooltip/Tooltip.stories.ts
- src/components/overlays/tooltip/Tooltip.vue
- src/composables/popper.ts
> feat(Menu): implement menu component

- src/components/tables/DataTable.vue
> fix(DataTable): fix sorting for BigNumber value

- example/cypress/e2e/forms/slider.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/SliderView.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/forms/radio-button/radio/Radio.vue
- src/components/forms/slider/Slider.spec.ts
- src/components/forms/slider/Slider.stories.ts
- src/components/forms/slider/Slider.vue
- src/components/forms/switch/Switch.vue
- src/components/index.ts
> feat(Slider): create Slider component

- example/cypress/e2e/accordions.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/AccordionView.vue
- src/components/accordions/accordion/Accordion.spec.ts
- src/components/accordions/accordion/Accordion.vue
- src/components/accordions/accordions/Accordions.spec.ts
- src/components/accordions/accordions/Accordions.stories.ts
- src/components/accordions/accordions/Accordions.vue
- src/components/index.ts
- src/components/tabs/tabs/Tabs.spec.ts
> feat(Accordions): implement accordions component

- example/src/views/DataTableView.vue
- src/components/forms/checkbox/Checkbox.vue
- src/components/tables/DataTable.vue
> feat(DataTable): allow shift selection for table checkboxes

- example/cypress/e2e/overlays/bottom-sheet.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/BottomSheetView.vue
- package.json
- src/components/forms/text-area/RuiTextArea.vue
- src/components/forms/text-field/RuiTextField.vue
- src/components/index.ts
- src/components/overlays/bottom-sheet/RuiBottomSheet.spec.ts
- src/components/overlays/bottom-sheet/RuiBottomSheet.stories.ts
- src/components/overlays/bottom-sheet/RuiBottomSheet.vue
- src/components/overlays/dialog/RuiDialog.spec.ts
- src/components/overlays/dialog/RuiDialog.vue
- src/components/overlays/menu/RuiMenu.spec.ts
- src/components/overlays/tooltip/RuiTooltip.spec.ts
- tests/setup-files/setup.ts
- vitest-globals.d.ts
> Sync with compat

- example/package.json
- package.json
> chore: release v0.16.0

- example/cypress/e2e/overlays/navigation-drawer.cy.ts
- example/cypress/e2e/overlays/notification.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/NavigationDrawerView.vue
- example/src/views/NotificationView.vue
- src/components/index.ts
- src/components/overlays/dialog/RuiDialog.vue
- src/components/overlays/navigation-drawer/RuiNavigationDrawer.spec.ts
- src/components/overlays/navigation-drawer/RuiNavigationDrawer.stories.ts
- src/components/overlays/navigation-drawer/RuiNavigationDrawer.vue
- src/components/overlays/notification/RuiNotification.spec.ts
- src/components/overlays/notification/RuiNotification.stories.ts
- src/components/overlays/notification/RuiNotification.vue
- src/utils/helpers.ts
> feat: introduce notification component

- src/composables/theme.ts
> fix(Theme): fix slow app when the theme is changed

- example/cypress/e2e/chip.cy.ts
- example/src/views/ChipView.vue
- src/components/chips/RuiChip.vue
- src/components/overlays/menu/RuiMenu.vue
> Minor fixes

- example/cypress/e2e/forms/auto-complete.cy.ts
- example/src/App.vue
- example/src/router/index.ts
- example/src/views/MenuView.vue
- src/__test__/options.ts
- src/components/forms/select/RuiMenuSelect.spec.ts
- src/components/forms/select/RuiMenuSelect.stories.ts
- src/components/forms/select/RuiMenuSelect.vue
- src/components/overlays/menu/RuiMenu.spec.ts
- src/components/overlays/menu/RuiMenu.stories.ts
- src/components/overlays/menu/RuiMenu.vue
- src/components/tables/RuiTablePagination.vue
- src/composables/dropdown-menu.ts
- src/composables/popper.ts
- src/utils/helpers.ts
- Add missing properties and replace showDetails with hideDetails
Closes #(issue_number)
> refactor(Menu)!: sync changes from compat and fix listeners

- example/src/views/AutoCompleteView.vue
- example/src/views/BottomSheetView.vue
- example/src/views/DialogView.vue
- src/components/overlays/bottom-sheet/RuiBottomSheet.spec.ts
- src/components/overlays/bottom-sheet/RuiBottomSheet.stories.ts
- src/components/overlays/dialog/RuiDialog.spec.ts
- src/components/overlays/dialog/RuiDialog.stories.ts
- src/components/overlays/dialog/RuiDialog.vue
> refactor!: replace v-on with attrs and v-bind

- scripts/generate-icons.mjs
- src/components/alerts/RuiAlert.stories.ts
- src/components/alerts/RuiAlert.vue
- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
- src/components/forms/auto-complete/RuiAutoComplete.vue
- src/components/forms/select/RuiMenuSelect.spec.ts
- src/components/icons/RuiIcon.stories.ts
- src/components/overlays/badge/RuiBadge.stories.ts
- src/components/overlays/menu/RuiMenu.vue
- src/utils/is-equal.ts
> Sync fixes from compat

- example/src/data/options.ts
- example/src/views/AutoCompleteView.vue
- example/src/views/MenuView.vue
- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
- src/components/forms/auto-complete/RuiAutoComplete.stories.ts
- src/components/forms/auto-complete/RuiAutoComplete.vue
- src/components/forms/radio-button/radio-group/RuiRadioGroup.vue
- src/components/forms/select/RuiMenuSelect.spec.ts
- src/components/forms/select/RuiMenuSelect.stories.ts
- src/components/forms/select/RuiMenuSelect.vue
- src/components/tabs/tabs/RuiTabs.vue
- src/composables/dropdown-menu.ts
> Fix v-for support in RuiTabs/RatioButtonGroup

- src/components/tabs/tab-items/RuiTabItems.vue
> fix(RuiTabItems): allow v-for content in RuiTabItems

- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
- src/components/forms/auto-complete/RuiAutoComplete.vue
- src/composables/dropdown-menu.ts
Closes #(issue_number)
Syncing the changes from compat
> fix(AutoComplete): fix UX to open menu after autocomplete focus

- example/src/views/TextAreaView.vue
- src/components/forms/text-area/RuiTextArea.spec.ts
- src/components/forms/text-area/RuiTextArea.stories.ts
- src/components/forms/text-area/RuiTextArea.vue
> fix(TextArea): update broken v-model event/property

- src/components/accordions/accordion/RuiAccordion.vue
- src/components/accordions/accordions/RuiAccordions.vue
- src/components/alerts/RuiAlert.vue
- src/components/buttons/button-group/RuiButtonGroup.vue
- src/components/buttons/button/RuiButton.vue
- src/components/cards/RuiCard.vue
- src/components/cards/RuiCardHeader.vue
- src/components/color-picker/RuiColorBoard.vue
- src/components/color-picker/RuiColorDisplay.vue
- src/components/color-picker/RuiColorHue.vue
- src/components/color-picker/RuiColorInput.vue
- src/components/color-picker/RuiColorPicker.vue
- src/components/divider/RuiDivider.vue
- src/components/forms/auto-complete/RuiAutoComplete.vue
- src/components/forms/radio-button/radio-group/RuiRadioGroup.vue
- src/components/forms/select/RuiMenuSelect.vue
- src/components/forms/select/RuiSimpleSelect.vue
> fix: manually handle attribute inheritance for components

- src/components/tables/RuiTablePagination.vue
> fix(DataTable): disable pagination navigation when loading

- src/components/tabs/tab/RuiTab.vue
- src/components/tabs/tabs/RuiTabs.spec.ts
- src/components/tabs/tabs/RuiTabs.vue
> fix(Tabs): custom tab-value not working

- src/components/tables/RuiTablePagination.vue
> style(DataTable): fix overflowing table footer indicator

- example/package.json
- package.json
> chore: release v1.0.0-beta.10

- package.json
- pnpm-lock.yaml
- scripts/dist-build.mjs
- scripts/generate-icons.mjs
- scripts/prepare.mjs
> chore: simplify build scripts

- src/components/buttons/button/RuiButton.vue
> fix(RuiButton): adds text-nowrap to label

- example/src/views/TabView.vue
- src/components/tabs/tab-items/RuiTabItems.vue
- src/components/tabs/tabs/RuiTabs.vue
> fix(Tabs): issue where Tab inside Fragment doesn't detected

- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
- src/components/forms/auto-complete/RuiAutoComplete.vue
> fix(Autocomplete): prevent input to be updated while menu still opened

- example/package.json
- package.json
> chore: release v1.0.0-beta.12

- package.json
- pnpm-lock.yaml
- scripts/build-web-types.mjs
- scripts/dist-build.mjs
- src/consts/colors.ts
Closes #(issue_number)
Needs some check to make sure that all is well.
> feat: add web-types to package

- example/package.json
- package.json
> chore: release v1.0.0

- src/composables/sticky-header.ts
> fix(DataTable): fix column and body position not sync

- src/components/overlays/tooltip/RuiTooltip.vue
> feat(Tooltip): introduce persistOnTooltipHover prop

- src/components/overlays/tooltip/RuiTooltip.vue
> feat(Tooltip): expose onClose to allow closing programatically

- example/package.json
- package.json
> chore: release v1.1.0

- src/composables/popper.ts
> feat(Tooltip): allow onClose without timeout

- src/components/buttons/button-group/RuiButtonGroup.vue
> fix(ButtonGroup): fix dynamic children tracking

- example/package.json
- package.json
> chore: release v1.1.2

- example/package.json
- package.json
- src/components/overlays/dialog/RuiDialog.vue
> Fix z-index affecting globally all dialogs

- src/components/overlays/dialog/RuiDialog.vue
> fix(Dialog): inherit attributes

- example/src/views/AutoCompleteView.vue
- src/components/forms/auto-complete/RuiAutoComplete.vue
- src/components/forms/select/RuiMenuSelect.vue
- src/composables/dropdown-menu.ts
> fix(AutoComplete): customValue and returnObject compatibility

- example/package.json
- package.json
> chore: release v1.2.4

- src/components/tabs/tab-items/RuiTabItems.vue
> fix(Tab): wrong direction & remove unwanted scroll while moving

- example/package.json
- package.json
> chore: release v1.2.5

- example/src/views/RadioView.vue
- src/components/forms/radio-button/radio-group/RuiRadioGroup.spec.ts
- src/components/forms/radio-button/radio-group/RuiRadioGroup.stories.ts
- src/components/forms/radio-button/radio-group/RuiRadioGroup.vue
- src/components/forms/radio-button/radio/RuiRadio.stories.ts
- src/components/forms/radio-button/radio/RuiRadio.vue
> fix(Radio): use generic type for Radio modelValue

- example/src/views/TextFieldView.vue
- src/components/forms/revealable-text-field/RuiRevealableTextField.stories.ts
- src/components/forms/text-field/RuiTextField.spec.ts
- src/components/forms/text-field/RuiTextField.stories.ts
- src/components/forms/text-field/RuiTextField.vue
> fix(TextField): clearable prop not showing the clear icon

- src/components/forms/text-area/RuiTextArea.spec.ts
- src/components/forms/text-area/RuiTextArea.vue
> fix(TextArea): adjust styling for clear icon

- src/components/overlays/menu/RuiMenu.vue
> fix(Menu): stop propagation when pressing escape button

- src/components/chips/RuiChip.vue
- src/components/forms/checkbox/RuiCheckbox.vue
- src/components/forms/radio-button/radio/RuiRadio.vue
- src/components/forms/revealable-text-field/RuiRevealableTextField.vue
- src/components/forms/slider/RuiSlider.vue
- src/components/forms/switch/RuiSwitch.vue
- src/components/forms/text-area/RuiTextArea.vue
- src/components/forms/text-field/RuiTextField.vue
- src/components/loaders/RuiSkeletonLoader.vue
- src/components/overlays/bottom-sheet/RuiBottomSheet.vue
- src/components/overlays/navigation-drawer/RuiNavigationDrawer.vue
- src/components/tables/RuiExpandButton.vue
- src/components/tabs/tab/RuiTab.vue
> refactor: replace useAttrs with $attrs

- example/cypress/e2e/data-table.cy.ts
- src/components/tables/RuiDataTable.spec.ts
- src/components/tables/RuiDataTable.vue
> feat(DataTable): also show the navigation on top

- src/components/forms/revealable-text-field/RuiRevealableTextField.spec.ts
- src/components/forms/text-field/RuiTextField.spec.ts
- vite.config.ts
> Test fixes

- example/package.json
- package.json
- pnpm-lock.yaml
> feat: increase minimum required versions of vue/vueuse

- src/components/tabs/tab/RuiTab.spec.ts
- src/components/tabs/tab/RuiTab.vue
- src/components/tabs/tabs/RuiTabs.spec.ts
- src/components/tabs/tabs/RuiTabs.stories.ts
- src/components/tabs/tabs/RuiTabs.vue
> feat(Tabs): props for change indicator position

- src/components/tables/RuiDataTable.vue
- src/components/tables/RuiTablePagination.vue
> fix(DataTable): make header pagination position fixed

- src/components/forms/text-field/RuiTextField.vue
> fix(TextField): add white background

- src/components/forms/text-field/RuiTextField.vue
> fix(TextArea): add white background

- example/src/auto-imports.d.ts
- example/src/components/ComponentGroup.vue
- example/src/utils/index.ts
- example/src/views/CheckboxView.vue
- example/src/views/LoaderView.vue
- example/src/views/SwitchView.vue
- example/src/views/TabView.vue
- example/src/views/TooltipView.vue
> Changing a few more examples to use data generation instead

- example/cypress/e2e/overlays/menu.cy.ts
- src/components/cards/RuiCard.vue
Closes https://github.com/rotki/ui-library/issues/289
> feat(Card): add content-class prop

- example/src/views/NavigationDrawerView.vue
- src/components/overlays/dialog/RuiDialog.vue
- src/components/overlays/navigation-drawer/RuiNavigationDrawer.vue
> style: blur backdrop for dialog overlay

- example/package.json
- package.json
> chore: release v1.7.1

- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
> test(AutoComplete): add test for selection visibility behavior

- src/components/color-picker/RuiColorDisplay.vue
- src/components/color-picker/RuiColorPicker.spec.ts
> refactor: update test selector

- example/package.json
- package.json
> chore: release v1.8.2

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
> ci: update actions configuration

- src/components/steppers/RuiFooterStepper.vue
- src/components/tabs/tabs/RuiTabs.vue
> fix(FooterStepper): wrong navigation icon

- example/package.json
- package.json
> chore: release v1.12.2

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
- example/package.json
- package.json
- pnpm-lock.yaml
- src/components/tables/RuiDataTable.vue
> chore: update vue-tsc

- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
- src/components/forms/auto-complete/RuiAutoComplete.vue
> fix(AutoComplete): onEnter should trigger the form submit

- eslint.config.js
- example/cypress/e2e/calendar.cy.ts
- example/src/router/index.ts
- example/src/views/CalendarView.vue
- src/components/calendar/RuiCalendar.spec.ts
- src/components/calendar/RuiCalendar.stories.ts
- src/components/calendar/RuiCalendar.vue
- src/components/calendar/RuiCalendarGrid.vue
- src/components/calendar/RuiCalendarHeader.vue
- src/components/calendar/RuiCalendarMenu.vue
- src/components/calendar/state.ts
- src/components/forms/text-field/RuiTextField.vue
- src/components/index.ts
> Add calendar component

- example/cypress/e2e/timepicker.cy.ts
- example/src/App.vue
- example/src/auto-imports.d.ts
- example/src/router/index.ts
- example/src/views/TimePickerView.vue
- src/components/components/RuiTimePicker.spec.ts
- src/components/components/RuiTimePicker.stories.ts
- src/components/components/RuiTimePicker.vue
- src/components/index.ts
> feat: introduce a time picker component

- example/cypress/e2e/button.cy.ts
- package.json
- pnpm-lock.yaml
- scripts/generate-icons.mjs
- src/components/icons/RuiIcon.spec.ts
- src/components/icons/RuiIcon.stories.ts
- src/components/icons/RuiIcon.vue
- src/components/overlays/badge/RuiBadge.spec.ts
> refactor(Icon): remove remix icon

- src/components/calendar/RuiCalendar.vue
- src/components/time-picker/RuiTimePicker.spec.ts
- src/components/time-picker/RuiTimePicker.vue
> style(DatePicker): update styling for calendar and timepicker

- src/stories/themes/shadow.mdx
Noticed an error in the storybook. Checked the other headings too, which were correct.
> docs: Change heading from Typography to Shadow

- example/package.json
- package.json
> chore: release v2.0.0

- src/components/overlays/menu/RuiMenu.spec.ts
- src/components/overlays/menu/RuiMenu.stories.ts
- src/components/overlays/menu/RuiMenu.vue
> feat(Menu): persist on content hover

- src/components/chips/RuiChip.spec.ts
- src/components/chips/RuiChip.vue
> feat(Chip): add 'contentClass' prop

- README.md
> chore: license badge added to documentation

- src/components/date-time-picker/RuiDateTimePicker.spec.ts
- src/components/date-time-picker/RuiDateTimePicker.stories.ts
- src/components/date-time-picker/RuiDateTimePicker.vue
> feat(DateTimePicker): add internal validation for min and max date

- README.md
- example/package.json
- example/src/main.ts
- example/src/views/DateTimePickerView.vue
- pnpm-lock.yaml
- src/components/date-time-picker/RuiDateTimePicker.vue
- src/composables/use-rui-i18n.ts
- src/i18n/keys.ts
- src/index.ts
> feat: add library translation support

- src/components/date-time-picker/RuiDateTimePicker.spec.ts
- src/components/date-time-picker/RuiDateTimePicker.vue
- src/components/date-time-picker/types.ts
- src/components/date-time-picker/use-input-handler.ts
- src/components/date-time-picker/use-keyboard-handler.ts
- src/index.ts
> Fix wrong hour placeholder and add paste parsing

- src/index.ts
- src/utils/blockie.spec.ts
- src/utils/blockie.ts
> feat(blockie): create blockie functionality

- src/components/forms/auto-complete/RuiAutoComplete.spec.ts
- src/components/forms/auto-complete/RuiAutoComplete.vue
> fix(Autocomplete): add search value to the menu when customValue=true

- src/components/forms/auto-complete/RuiAutoComplete.vue
Closes https://github.com/orgs/rotki/projects/11/views/3?pane=issue&itemId=123073730
> fix(Autocomplete): remove internal search debounce

- src/components/date-time-picker/RuiDateTimePicker.spec.ts
- src/components/date-time-picker/RuiDateTimePicker.vue
Required for https://github.com/rotki/rotki/pull/10449
> fix(DateTimePicker): clear input when clicking the clear button

- example/package.json
- package.json
> chore: release v2.6.3

- src/components/forms/checkbox/RuiCheckbox.vue
- src/style.scss
- src/theme/index.ts
- tailwind.config.ts
> fix(Checkbox): make the focus state more prominent
